# Generated by Django 4.0.5 on 2022-06-15 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='mandalName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.mandal'),
        ),
        migrations.AddField(
            model_name='mandal',
            name='districName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.district'),
        ),
        migrations.AlterField(
            model_name='city',
            name='cityName',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='district',
            name='districtName',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='mandal',
            name='mandalName',
            field=models.CharField(max_length=64),
        ),
    ]
