# Generated by Django 4.0.5 on 2022-06-15 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_city_mandalname_mandal_districname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='mandalName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.mandal'),
        ),
        migrations.AlterField(
            model_name='mandal',
            name='districName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.district'),
        ),
    ]
