# Generated by Django 4.0.5 on 2022-06-15 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_hospital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='cityname',
            new_name='cityName',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='districtname',
            new_name='districtName',
        ),
    ]
