# Generated by Django 4.0.5 on 2022-06-16 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_cityname_hospital_cityname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mandal',
            old_name='districName',
            new_name='districtName',
        ),
    ]
