# Generated by Django 4.0.5 on 2022-06-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_districname_mandal_districtname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatmentRealted', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='treatmentName',
            field=models.ManyToManyField(related_name='treatmentName', to='base.treatement'),
        ),
    ]
