# Generated by Django 4.0.5 on 2022-06-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_treatement_hospital_treatmentname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='hospitalName',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
