# Generated by Django 4.0.5 on 2022-06-17 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_hospital_hospitalname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='cityName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.city'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='districtName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.district'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='mandalName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.mandal'),
        ),
    ]
