# Generated by Django 4.0.5 on 2022-06-15 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_city_mandalname_alter_mandal_districname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalName', models.CharField(max_length=256)),
                ('cityname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.city')),
                ('districtname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.district')),
                ('mandalName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.mandal')),
            ],
            options={
                'ordering': ['-hospitalName'],
            },
        ),
    ]
